

#this is for making a docker  compose for mysql 

# docker compose version 
# Compose file versions support for  Docker 18.06.0+
# 3.7 
# Docker version 23.0.1
# docker-compose version 1.29.2,


version: '3.7'

#Puede haber tantos servicios como querramos; framework web, servidor web,
services:
  db:
    container_name: mysql 
    image: mysql:8.0
    cap_add:
      - SYS_NICE 
    restart: always
    environment: 
      - MYSQL_DATABASE=Test
      - NYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local








